dns-creds: ENC[AES256_GCM,data:pRdCTlBGV5bdcgNoVNTSFziYm1jc2oJw3+yc2A9JkbhhE2CyojwfRgIwt3xSOD0OAlLAdoNCy2nR33vg9EVdVruBw0voVpbNF0SY1m6Vihzr3i4y4OHFZf8Qxoxym5rn7zG2BLDFsOCcwvG4mecd1/m2mQz9DnOTICeALLZA1UPf4M8=,iv:G0D5vzqdbVLFdLRRkhpLxJbvaSPn/U2o0KJ4iIpxdso=,tag:reOv6mhtmGi3hrBIh+ZwUQ==,type:str]
sops:
    age:
        - recipient: age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDF4U3hQVWZPSWVnY3VO
            TTd4bHZ0TnBZNkthM1Y4bWJTVUFDU1B0QUhJCmRXZExCeTNDbVI0L3F2UEd6Q05Y
            bjNGbkhqTVhYNjl4bW9lTG1jdWVucjQKLS0tIE1USWpYWERzMlVveTNRSHZGTTBw
            VEdlQnZDMXJBZDgxYlZibUJScW00ODQKsNFx65Vi7IKEixeFkpwvG+AFh6c6mYf8
            /BrMcMQwSKOMQH7PA9sxQmcNbYtt1eZmrohUJIWADudFrGo8xSkm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T23:06:59Z"
    mac: ENC[AES256_GCM,data:MmYBm+/VEZhPIbZ7nGBlcYdsD0dJOw1moQPN+8W5vBY3L0v0O6h8yjUnaIWas/twsAi47TGzbFwQ+TGKqSXmfGjTrzXs+2t3ij4PcXpmcPpNFAeQfJ8KQEbB92KcDq0N5NgcHYE9Mo/a0BU8V1LBzxilQo+Vp+/HntL4sSe5+l0=,iv:ay3s8lUxWJZmkuZmxdNiexpISbQ4ajTHI7opyMxP7s4=,tag:PxFEknCqaP2iJkzmlErG/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
