dns-creds: ENC[AES256_GCM,data:zpfHHN0jD3OAUZ1xxStgghNIZu/N4HZufP4WC17D1S+Nj63VKktnZBRz2caKEXHkJT/9YrfG4xucUKVlEs2cGXXkKM3GiEN1FS8vcn+k/2H1pdP/7pylAqjYVEJb/2AijPAg3hO6Ro4dDncZ1oATPkx5WrPMaj5rdDwugs6oZBBheJbCuKJJYw==,iv:d6p+2pieLA5U/uJJinGUUndSlTPlEdod1ZYpAa0PEeY=,tag:jWgBonWrqHGhodj2tBcPIg==,type:str]
sops:
    age:
        - recipient: age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDF4U3hQVWZPSWVnY3VO
            TTd4bHZ0TnBZNkthM1Y4bWJTVUFDU1B0QUhJCmRXZExCeTNDbVI0L3F2UEd6Q05Y
            bjNGbkhqTVhYNjl4bW9lTG1jdWVucjQKLS0tIE1USWpYWERzMlVveTNRSHZGTTBw
            VEdlQnZDMXJBZDgxYlZibUJScW00ODQKsNFx65Vi7IKEixeFkpwvG+AFh6c6mYf8
            /BrMcMQwSKOMQH7PA9sxQmcNbYtt1eZmrohUJIWADudFrGo8xSkm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:18:51Z"
    mac: ENC[AES256_GCM,data:RjsElkP5jCLY2O90nUv7Jv9gQqb/dEeituHoeEdefe8Hh8Br5Hjh78Gaabo8lG3jMvh0UKOnfbH0pUUPbS15LBC3XV1Dfiwo6/hjK05HcE5q/6WlNqhM2LPzTRGeK+odpYAdiM5gPBV8oP/yqKp22naP8uFjFF4z4X0zuPm0hkk=,iv:RjM5Wxffv52h05LPE2gD3C5GVHEnh9JDhQ+rxJEqC80=,tag:QSiH7vyr2QphX9Ji/B4w+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
