dns-creds: ENC[AES256_GCM,data:i1SJ,iv:jzIKH2uZ+XV003DnLZwtU/i6w2dxAPAJQWU3ErBEEag=,tag:E1gZW/4fKENJt4Udi6eCjA==,type:str]
sops:
    age:
        - recipient: age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDF4U3hQVWZPSWVnY3VO
            TTd4bHZ0TnBZNkthM1Y4bWJTVUFDU1B0QUhJCmRXZExCeTNDbVI0L3F2UEd6Q05Y
            bjNGbkhqTVhYNjl4bW9lTG1jdWVucjQKLS0tIE1USWpYWERzMlVveTNRSHZGTTBw
            VEdlQnZDMXJBZDgxYlZibUJScW00ODQKsNFx65Vi7IKEixeFkpwvG+AFh6c6mYf8
            /BrMcMQwSKOMQH7PA9sxQmcNbYtt1eZmrohUJIWADudFrGo8xSkm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T19:07:45Z"
    mac: ENC[AES256_GCM,data:x0rOu4n+xlVeWFxc4NJ5Ah0pcaee4HEvbdeBW4lMahvuyKP0SvfTUst0qfB9GrOPFssv1VMq7NXaqpu7PWSUzwf7/6Hl/VIzolXvO1pTisX8S2toWEarcIWRXjzCxkBNcXOI3THaG4RRZQ8ZNs8MaxgYxdpIvur3JusoKQTNvns=,iv:BaizOk2FrQNbMvNQoHMpVB/NA7UHwRbwOT6nGdR4QwM=,tag:svP/1ARApoWBMDrO0AfG4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
