dns-creds: ENC[AES256_GCM,data:HSRovIq1xSJk5yT23ubwjbyDS1erQVGmWmXPsLejNhc/E45f/70Fvaf2h8qS/z1wEWwoy4uAkisHRBrveOMu7qf5ihybuDHvkGnosyV7INIvNAR51z5OqTqUp/oUC6Cs,iv:uk/xs5QRoNTZwogqjdZjs8m0SYz2alb+HlSwrYYdHO8=,tag:7rMwUu4VnZ3ujrFt5iXGGg==,type:str]
sops:
    age:
        - recipient: age16fjn06trywshgm5gg68d8zyr7x0tgdd2x22v92hrrtx806rq3sfs9xl5f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDF4U3hQVWZPSWVnY3VO
            TTd4bHZ0TnBZNkthM1Y4bWJTVUFDU1B0QUhJCmRXZExCeTNDbVI0L3F2UEd6Q05Y
            bjNGbkhqTVhYNjl4bW9lTG1jdWVucjQKLS0tIE1USWpYWERzMlVveTNRSHZGTTBw
            VEdlQnZDMXJBZDgxYlZibUJScW00ODQKsNFx65Vi7IKEixeFkpwvG+AFh6c6mYf8
            /BrMcMQwSKOMQH7PA9sxQmcNbYtt1eZmrohUJIWADudFrGo8xSkm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T14:38:39Z"
    mac: ENC[AES256_GCM,data:XMlqcnchp6J4a9Hoe7oL15mXuWRCJDL0nah6BmHobxPQClxaXv4413T9IvfAOSqWbiY8HuXEPSAHUVXQgUq1ksp1GpUEE4dFKOYmmGViF+bQ39S/ExgzseoFnQrBxTaoy69fefh83b/6m2JMCoj3+DhWgoet+gonqOBIBQBn6Xc=,iv:JQsvHt6Yq5SnUvE/ri09JIJ2JqHA0gfg2MNBK49kvHE=,tag:RL0gWzUCplKbPzNdy+ZSKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
